DataDog/synthetics-ci-github-action

README.md

We use secrets in the README example workflows, we should keep the consistency throughout.

Update README to recommend use of GitHub secrets

---

README.md

Updates `/cicd_testing/` to `/cicd_integrations` that update links in PR [12360]( https://github.com/DataDog/documentation/pull/12360).

Synthetics CI GitHub Action README Edit

---

README.md
action.yml
src/resolve-config.ts

Remove support for `tunnel` option which is currently not relevant in the context of Github Actions. 
There are no convenient way of maintaining a local server running during the action execution, if to be supported, the action itself should offer a wrapper around a custom server launch command.

[config] Remove support for `tunnel` option

---

LICENSE-3rdparty.csv

The comma from `Datadog, Inc` is viewed as a new column in the `LICENSE-3rdparty.csv` file.
And because of this, GitHub fails to render the CSV file as a table. It could also break other tooling.

Fix CSV table in LICENSE-3rdparty.csv

---

LICENSE
NOTICE

Our open-source repositories must use an Apache-2.0 license.

[license] Move from MIT to Apache-2.0

---

__tests__/main.test.ts
__tests__/resolve-config.test.ts
src/main.ts
src/resolve-config.ts

We are setting `config.variableStrings` using the value of the `variables` input.
However, since the Action uses `synthetics.executeTests` instead of `synthetics.execute` to run the tests, `config.variableStrings` is never parsed into `config.global.variables` (cf. [this part in datadog-ci](https://github.com/DataDog/datadog-ci/blob/0ee79438390f2ddca3d41251dc4984b3c7381e0c/src/commands/synthetics/command.ts#L194), which is only used when calling `synthetics.execute`).
This is why the variables set in the workflows are not actually used.
This PR fixes this behavior, by parsing the variables directly in the Action, using the `synthetics.utils.parseVariablesFromCli` function.

Fix `variables` input not being used

---

action.yml

This PR updates the using runtime to node16, rather than node12.
ref: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

Upgrade to use node16

---

README.md
package.json

The `v0.9.0` release didn't work as expected because the git tag `v0.9.0` was not set on the commit introducing the changes.
(I suspect the `git commit --amend` command to un-assign the tag from the amended commit)

Release `v0.9.1`

---

README.md
__tests__/main.test.ts
action.yml
src/fixtures.ts
src/main.ts
src/resolve-config.ts
src/utils.ts

Depends on: https://github.com/DataDog/datadog-ci/pull/774 (and the [corresponding bump](https://github.com/DataDog/synthetics-ci-github-action/pull/116))
This PR adds a `junit_report` input, so that you can build a JUnit XML report of the tests that were run.

Add `junit_report` input

---

yarn.lock

Fixes https://github.com/DataDog/synthetics-ci-github-action/security/dependabot/13

[dep] Bump json5 from 2.2.0 to 2.2.3

---

.eslintignore
.github/workflows/bump-datadog-ci.yml
.github/workflows/release-version.yml
ci/pull-request-comments.js

- #128 ←
- #129 
---
In order to automate bumping `datadog-ci` and releasing a new version of the CI integration, we are creating workflows which will simplify our current process.
This PR adds 2 manual workflows:
- One workflow to automatically create a PR to bump datadog-ci. This will later be triggered from the **datadog-ci repository**'s CI when a release is created, so that we don't forget to bump datadog-ci in the integrations.
- One workflow to automatically create a release PR with release notes as a description.
The 2 workflows are separated to give us more flexibility.

[ci] Add manual workflows for bump and release PRs

---

.github/workflows/release-version-on-merge.yml

- #128
- #129 ← 
---
This PR adds a workflow that will be automatically run when a release PR is merged.

[ci] Add workflow to automatically create a GitHub release

---

.github/workflows/bump-datadog-ci.yml
.github/workflows/release-version-on-merge.yml
.github/workflows/release-version.yml

[SYNTH-8788](https://datadoghq.atlassian.net/browse/SYNTH-8788)
[SYNTH-8789](https://datadoghq.atlassian.net/browse/SYNTH-8789)
In #128 and #129 were added 3 workflows for release automation.
However, they were using the `GITHUB_TOKEN` that is available in workflows by default.
But we then noticed this:
> When you use the repository's `GITHUB_TOKEN` to perform tasks, events triggered by the `GITHUB_TOKEN`, with the exception of `workflow_dispatch` and `repository_dispatch`, will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's `GITHUB_TOKEN`, a new workflow will not run even when the repository contains a workflow configured to run when `push` events occur. …

[ci] Use the "CI Integrations Release Automation" github app

---

README.md

As can be seen here, the latest version is v3: https://github.com/actions/checkout
This commit updates the readme to indicate the use of the latest version.

Use the latest GHA checkout action

---

LICENSE-3rdparty.csv
package.json
src/resolve-config.ts
yarn.lock

- #122 
- #134 ←
---
The `clipanion` dependency was used to import the `BaseContext` interface only.
But we can just do pass `process` directly: `{ context: process}` (we do it [in datadog-ci](https://github.com/DataDog/datadog-ci/blob/e8f18c0030bf54ca6f81e00d58d60cb6718b6194/src/commands/synthetics/run-test.ts#L279)).

Remove superfluous dependency

---

README.md
__tests__/resolve-config.test.ts
action.yml
src/resolve-config.ts

This PR adds a `polling_timeout` input to be able to set a value of `pollingTimeout` different than the default of 30 minutes ([official documentation](https://docs.datadoghq.com/continuous_testing/cicd_integrations/configuration?tab=npm#global-configuration-file-options)).
This input must be an integer.

Add `polling_timeout` input

---

.github/workflows/release-version.yml

The "Bump CI integration version" step now bumps anything that can be bumped, including references to the bumped version (e.g. in the README). It's now this task that has a step output with the tag name for the new version.
I renamed `VERSION_TAG` to `NEW_VERSION_TAG` to avoid any confusion with `OLD_VERSION_TAG`.
No remaining references to the old `commit-new-version` step ID.
```bash
grep -r "commit-new-version" .
```
No remaining references to the old `VERSION_TAG` bash variable/step output.
```bash
grep -r -E "\bVERSION_TAG" .
```

[ci] Update README with `release-version.yml`

---

__tests__/main.test.ts
src/resolve-config.ts

Following https://github.com/DataDog/datadog-ci/pull/887, `DEFAULT_COMMAND_CONFIG` is now exported by datadog-ci.
This PR replaces this integration's local default config, with a usage of `synthetics.DEFAULT_COMMAND_CONFIG`.
It also updates one unit test, because we don't have a `DEFAULT_CONFIG` object anymore.

Use default command config exported by datadog-ci

---

__tests__/resolve-config.test.ts
src/resolve-config.ts

This PR moves the `polling_timeout` input from the root of the config to the `global` field of the config, where it's expected by datadog-ci: 
datadog-ci pushes pollingTimeout from root config to global config if pollingTimeout is undefined in the global config
- the implementation: https://github.com/DataDog/datadog-ci/blob/8000318d70fd8af22b0e377b27078762b562efb7/src/commands/synthetics/command.ts#L228
- the test: https://github.com/DataDog/datadog-ci/blob/65ffde5d90474af5930da4c2faf016505b70bff9/src/commands/synthetics/__tests__/cli.test.ts#L173-L186

[SYNTH-9893] move polling_timeout input to the global config field

---

__tests__/main.test.ts
__tests__/resolve-config.test.ts
src/resolve-config.ts

Following https://github.com/DataDog/synthetics-ci-github-action/pull/155, we eventually found that the solution wasn't satisfactory: both the `config.pollingTimeout` and `config.global.pollingTimeout` should be populated.
`config.pollingTimeout` is used to compute the `maxPollingTimeout` used by datadog-ci to wait for the batch result, but is never sent to the API: https://github.com/DataDog/datadog-ci/blob/1e7a4ae91d25a52434af622ceda1556c06b1c397/src/commands/synthetics/run-test.ts#L148
`config.global.pollingTimeout` overrides the `pollingTimeout` individually in tests, which is used by the API to know when a batch times out: https://github.com/DataDog/datadog-ci/blob/1e7a4ae91d25a52434af622ceda1556c06b1c397/src/commands/synthetics/run-test.ts#L50-L53

[SYNTH-9893] populate both pollingTimeout in config

---

.github/workflows/e2e/global.config.json

The `timeout` option was removed a long time ago (cf. [here](https://github.com/DataDog/datadog-ci/blob/aed788742c95396eb3c898799dd64c712df2edb2/src/commands/synthetics/README.md) and [here](https://github.com/DataDog/datadog-ci/blob/aed788742c95396eb3c898799dd64c712df2edb2/src/commands/synthetics/run-test.ts#L58) to go back in time).
This PR updates the config to [the right  `pollingTimeout` config](https://github.com/DataDog/datadog-ci/blob/c6ce9dcf152521adb118c15b75434f645e22ab6a/src/commands/synthetics/run-test.ts#L156).

[ci] Update config files

---

__tests__/main.test.ts
src/main.ts

Currently, some newlines are missing between the summary and the success message.
Notice the `Total Duration: 16sDatadog Synthetics tests succeeded`:
After this PR:
While `core.info()` is just a wrapper for `process.stdout.write(message + os.EOL)`, `core.setFailed()` issues [an error command](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message), which is displayed differently so we don't need to add newlines for this function:

Add newlines before success message

---

yarn.lock

The `semver` package now has a backported fix for all latest major versions: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw 
Use the appropriate version for majors 5, 6 and 7.

[dep] Use latest `semver@5,6,7`

---

package.json
yarn.lock

Bump Jest to 29 to support modules (like axios), which [use the new `exports` property in package.json](https://github.com/axios/axios/blob/7009715369a50740ba2ce00534012c1caf269ad2/package.json#L7-L20).
This PR will fix the failing CI in https://github.com/DataDog/synthetics-ci-github-action/pull/201.
```bash
● Test suite failed to run
Jest encountered an unexpected token
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
By default "node_modules" folder is ignored by transformers.
Here's what you can do:
• If you are trying to use ECMAScript …
```

[dep] Upgrade to Jest 29

---

__tests__/main.test.ts

Using `core.setFailed()` makes the CI fail (for Node.js 20.x only) because this function [sets `process.exitCode` to `1`](https://github.com/actions/toolkit/blob/fe3e7ce9a7f995d29d1fcfd226a32bca407f9dc8/packages/core/src/core.ts#L221).
Related issue: https://github.com/jestjs/jest/issues/14501
So, mocking the implementation of `setFailed` to a noop **is required**, since simply spying only registers the calls of that function.
Here is [what was happening](https://github.com/DataDog/synthetics-ci-github-action/actions/runs/6828161206/job/18571760480#step:7:47):

[test] Do not set `process.exitCode` in tested code

---

.github/workflows/unit-tests.yml
package.json
yarn.lock

Fixes [the following issue](https://github.com/DataDog/synthetics-ci-github-action/actions/runs/7873214387/job/21480049366) when doing `yarn package`:
```js
ncc: Version 0.31.1
ncc: Compiling file index.js into CJS
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:68:1[9](https://github.com/DataDog/synthetics-ci-github-action/actions/runs/7873214387/job/21480049366#step:9:10))
at Object.createHash (node:crypto:138:[10](https://github.com/DataDog/synthetics-ci-github-action/actions/runs/7873214387/job/21480049366#step:9:11))
at hashOf (/home/runner/work/synthetics-ci-github-action/synthetics-ci-github-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1855992)
at ncc (/home/runner/work/synthetics-ci-github-action/synthetics-ci-git …
```

[dep] Upgrade `@vercel/ncc`

---

yarn.lock

Fix https://github.com/DataDog/synthetics-ci-github-action/security/dependabot/38

[dep] Bump tar to `6.2.1`

---

.github/workflows/e2e/global.config.json
README.md
__tests__/main.test.ts
__tests__/resolve-config.test.ts
src/fixtures.ts
src/resolve-config.ts

See https://github.com/DataDog/datadog-ci/pull/1285

Remove usage of deprecated `global`

---

README.md

Update `actions/checkout@v3` to `actions/checkout@v4`

docs(readme): update examples with latest checkout action version

---

yarn.lock

- https://github.com/DataDog/synthetics-ci-github-action/security/dependabot/45
- https://github.com/DataDog/synthetics-ci-github-action/security/dependabot/39
- https://github.com/DataDog/synthetics-ci-github-action/security/dependabot/40
Commands I ran:
```sh
yarn set resolution cross-spawn@npm:^7.0.0 7.0.6
yarn set resolution google-gax@npm:^4.0.3 4.3.8
yarn set resolution braces@npm:^3.0.1 3.0.3
```

[dep] Upgrade deps to fix 3 vulnerabilities

---

__tests__/main.test.ts
src/main.ts

This PR reverts https://github.com/DataDog/synthetics-ci-github-action/pull/162 because there is no reason to do it anymore:

Remove redundant newlines in success output

---

__tests__/main.test.ts

This PR mocks `getOrgSettings` and fixes temporary files not getting cleaned up on test failure.

[ci] Fix slow unit tests

---

.github/workflows/run-e2e-tests.yml
src/resolve-config.ts

After #316, we need to inform users.
The warning was already provided by GitHub. This PR adds an error message.

Add error message to inform about new input format
